apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: https
  - appProtocol: http
    name: healthz
    nodePort: 30254
    port: 10254
    protocol: TCP
    targetPort: 10254
  type: NodePort
